name: Run Backfill
run-name: Triggering backfill of ${{ inputs.collection }} on ${{ inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      collection:
        type: choice
        options:
          - all
          - exclusions
          - facilityprofiles
          - agentprofiles
          - shifts
          - priorityaccesses
        default: exclusions
        required: true
      environment:
        type: choice
        options:
          - staging
          - development
        default: development
        required: true
      start_date:
        type: string
        required: false
jobs:
  backfill-all-collections:
    if: ${{ inputs.collection == 'all' }}
    strategy:
      matrix:
        collection: ['exclusions', 'facilityprofiles', 'agentprofiles', 'shifts', 'priorityaccesses']
    uses: ./.github/workflows/backfill-collection.yml
    with:
      collection: ${{ matrix.collection }}
      environment: ${{ inputs.environment }}
      start_date: ${{ inputs.start_date }}