name: Run Backfill
run-name: Triggering backfill of ${{ inputs.collection }} on ${{ inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      collection:
        type: choice
        options:
          - 'all collections'
          - exclusions
          - facilityprofiles
          - agentprofiles
          - shifts
          - priorityaccesses
        default: exclusions
        required: true
      environment:
        type: choice
        options:
          - staging
          - development
        default: development
        required: true
      start_date:
        type: string
        required: false
jobs:
  backfill-all-collections:
    if: ${{ inputs.collection == 'all collections' && inputs.start_date != '' }}
    strategy:
      matrix:
        collection: [ 'exclusions', 'facilityprofiles', 'agentprofiles', 'shifts', 'priorityaccesses' ]
    uses: ./.github/workflows/backfill-collection.yml
    with:
      collection: ${{ matrix.collection }}
      environment: ${{ inputs.environment }}
      start_date: ${{ inputs.start_date }}
  inform-requirement-of-date-to-backfill-all-collections:
    if: ${{ inputs.collection == 'all collections' && inputs.start_date == '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Inform requirement of date
        run: |
          echo "start_date is required to run backfill for all collections"
          exit 1
  backfill-one-collection:
    if: ${{ inputs.collection != 'all collections' }}
    uses: ./.github/workflows/backfill-collection.yml
    with:
      collection: ${{ inputs.collection }}
      environment: ${{ inputs.environment }}
      start_date: ${{ inputs.start_date }}